language: rust
sudo: required
env:
  global:
  - CRATE_NAME=fastatools
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
    os: linux
    dist: bionic
  - env: TARGET=x86_64-unknown-linux-musl
    os: linux
    dist: bionic
before_install:
- set -e
- rustup self update
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- sh ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: giTZP4azNCV9ksXrEINWkUUy3Ma9Cicxix5in1kFpo96MDfTH8CW/thNMDsrs8jWVYzYoRrwxO+oaRNnwfo3qz3NkuecAwvjNlrhuco5kLEI2uVpI4ZY47MwqyeKBpWDK4PABse+7ERUvEKBZ1v5dBkguRo18MbpnahW5+Z62hhfbegc7bum4AFGgYg+MUorhNCGLTDsIsVs0TBeEMUsThn2ar0s5FHzc4yXtaIJpcfUauEmzKYVh3YIcT8H5KL3JXv9PIvg1cK1c2XvhyH1bEzLv/nVip0W73QpflCg7iD73hW1VCAmEH6Zy7ccRXcNeZ7eSOAPrVXIBkWWr04Zh6FGWcJeC+2ssY6H5gc6WbqYG+bRw659ttXQlPBwik+q/zeSUSsY7Gne+86ma8R/EoQ0RK6ZaQw84+r0xrhdWWWkXFvryX6tgkMzvRNeurGBXOalF+yPrJhSxPMS2urApSG36mbqc9DbsVa7FJyq2/Zb2pJ3MAaL/9US2UsuIesUqOXndIkbxXp2fo781JAsZPAI6gIBOFf1IuW+zVZkzh36UQutrqxJWPQSNU8OKHOo6eSZskfpO9cz+KFIVPsYjtaRNFeYnGQlB+QUz5qr+tCl0B8E9xZPl2zfa9dXMwDGchv6ZiDYKlKfX743/Dc7yQiIoh+U2cMy+sRoIA1ok1U=
  skip_cleanup: 'true'
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_success: never
